

## [START runtime]
#runtime: nodejs10
#handlers:
#- url: /
#  static_files: nenglo/index.html
#  upload: nenglo/index.html
#- url: /
#  static_dir: nenglo
## [END runtime]




runtime: nodejs10
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist


