

## [START runtime]
#runtime: nodejs10
#handlers:
#- url: /
#  static_files: nenglo/index.html
#  upload: nenglo/index.html
#- url: /
#  static_dir: nenglo
## [END runtime]




runtime: nodejs10
#handlers:
#- url: /
#  static_files: dist/nenglo/index.html
#  upload: dist//nenglo/index.html
#- url: /
#  static_dir: dist
#
